### users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Katie R",
  "email": "katie@email.com",
  "password": "password",
  "password_confirmation": "password"
}